apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mk5vjmy9b-python 
  janus-idp.io/tekton: mk5vjmy9b-python
  backstage.io/kubernetes-id: mk5vjmy9b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mk5vjmy9b-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml